### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by WPDevHQ** [ingeniousweb/ParticleJs-WP-Plugin#1]
How does this work in relation to Elementor?

**Comment by munirkamal** [comment]
I have tried it with elementor. The elementor sections doesn't allow to assign an ID and this scripts works only with an ID, therefore i wasn't able to make it work with elementor yet. May be you can come-up with a workaround? I haven't much tried myself :(

**Comment by WPDevHQ** [comment]
Ah OK.

Thanks for adding the tutorial link - will take a look and see what can be done to work it with Elementor.
